version: '3.8'

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword123
      - DOCKER_INFLUXDB_INIT_ORG=bitpulse
      - DOCKER_INFLUXDB_INIT_BUCKET=whale_analytics
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=cetoduhtCKuV326JM41RiCZLo2Hk6hvndook0AnuGLBQfJ_zYvkInkf3VMdLx3PeavNwdmjPdMB9FJbYHibmBA==
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  influxdb-data:
  influxdb-config: